= Example for Monitoring Confluent Platform with Prometheus and Grafana based on Docker

DISCLAIMER: This project is for demonstration purposes only. Using the concept in production is highly discouraged. Use at your own risk.

== Preconditions

This project has been tested with Java version 17 and Gradle version TODO

== Running Confluent Platform
Change to folder `cluster`.

Start the containers by running:
```
docker-compose up -d
```

Stopping the containers:
```
docker-compose down
```

Cleaning up (CAREFUL: THIS WILL DELETE ALL UNUSED VOLUMES):
```
docker volumes prune
```

== Building the Producers
Initialize by running
```
gradle wrapper
```

Build Jar including all libraries with:
```
./gradlew shadowJar
```

== Running the transactional producer
Change to the "clients" folder. Then use the following commands to run the code:

```
./gradlew -p producer-transactional run
```

== Some helpful commands
Consume from the topic like this:

```shell
kafka-console-consumer --bootstrap-server localhost:9092 --topic topic-1 --from-beginning
```

You can delete the auto-created topic like this:

```shell
kafka-topics --bootstrap-server localhost:9092 --delete --topic topic-1
```
