/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.csta.examples.transactions.consumer.transactional;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class TransactionalConsumer {
/*     @Test void testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage());
    } */
}
