/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.csta.examples.transactions.java-application-conventions")
}

dependencies {
}

application {
    // Define the main class for the application.
    mainClass.set("io.confluent.csta.examples.transactions.producer.transactionalchaos.TransactionalChaosProducer")
}

tasks.run<JavaExec> {
    args(listOf("../producer-transactional.properties"))
}
