/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.csta.examples.transactions.java-application-conventions")
}

dependencies {
    //implementation("org.apache.kafka:kafka-clients:3.6.1")
}

application {
    // Define the main class for the application.
    mainClass.set("io.confluent.csta.examples.transactions.kstreams.KStreamsHeaderForward")
}

tasks.run<JavaExec> {
    args(listOf("../kstreams-header-forward.properties"))
}
